#ifndef XULWIN_TEST_CONFIG_INCLUDED_H
#define XULWIN_TEST_CONFIG_INCLUDED_H


#define FORCE_MESSAGEBOX_LOGGING 1
#define TEST_WITH_MOZILLA_XULRUNNER 0


#endif // XULWIN_TEST_CONFIG_INCLUDED_H
